import 'package:flutter/material.dart';


class MyTextTheme {
  static const _color1d = Color(0xff1d1d1d);
  static const lightTextTheme = TextTheme(
      displayLarge: TextStyle(
          color: Color(0xFF1e1e1e),
          fontFamily: 'Outfit',
          fontWeight: FontWeight.w700),
      displayMedium: TextStyle(
          color: Color(0xFF1e1e1e),
          fontFamily: 'Outfit',
          fontSize: 16,
          fontWeight: FontWeight.w500),
      displaySmall: TextStyle(
          color: Color(0xFF1e1e1e),
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.normal),
      bodySmall: TextStyle(
        color: Color(0xFF1e1e1e),
        fontFamily: 'Outfit',
        fontSize: 14,
      ),
      bodyMedium: TextStyle(
          color: Color(0xFF1e1e1e),
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.w500),
      bodyLarge: TextStyle(
          color: Color(0xFF1e1e1e),
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.w700),
      titleLarge: TextStyle(
          color: _color1d,
          fontFamily: 'Outfit',
          fontSize: 24,
          fontWeight: FontWeight.w700),
      titleMedium: TextStyle(
          color: _color1d,
          fontFamily: 'Outfit',
          fontSize: 16,
          fontWeight: FontWeight.w700),
      titleSmall: TextStyle(
          color: _color1d,
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.w300),
      labelLarge: TextStyle(
          color: _color1d,
          fontFamily: 'Outfit',
          fontSize: 16,
          fontWeight: FontWeight.w700),
      labelMedium: TextStyle(
          color: Color(0xFF1e1e1e),
          fontFamily: 'Outfit',
          fontSize: 16,
          fontWeight: FontWeight.w500));

  static const darkTextTheme = TextTheme(
      displayLarge: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontWeight: FontWeight.w700),
      displayMedium: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 16,
          fontWeight: FontWeight.w500),
      displaySmall: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.normal),
      bodySmall: TextStyle(
        color: Color(0xFFEAEDEF),
        fontFamily: 'Outfit',
        fontSize: 14,
      ),
      bodyMedium: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.w500),
      bodyLarge: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.w700),
      titleLarge: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 24,
          fontWeight: FontWeight.w700),
      titleMedium: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 18,
          fontWeight: FontWeight.w500),
      titleSmall: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 14,
          fontWeight: FontWeight.w300),
      labelLarge: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 16,
          fontWeight: FontWeight.w700),
      labelMedium: TextStyle(
          color: Color(0xFFEAEDEF),
          fontFamily: 'Outfit',
          fontSize: 16,
          fontWeight: FontWeight.w500));
}
